load("@rules_java//java:defs.bzl", "java_import")

java_import(
    name = "antlr4_runtime",
    jars = [":antlr4-runtime-4.8-2-SNAPSHOT.jar"],
    visibility = ["//visibility:public"],
    deps = [],
)
